name: NginxMC
version: 1.8.22a preview build
description: a non-minecraft deluxe core plugin for siamcraft
authors: [_StarChaser, Ponlawat]
main: me.starchaser.nginxmc.bukkit.core
load: POSTWORLD
softdepend:
  - Multiverse-Core
  - MVdWPlaceholderAPI
  - PlaceholderAPI
commands:
  nginx:
    description: Main commands
    aliases: [nginx]
    usage: /nginxmc
  coins:
    description: Main commands
    aliases: [bal,balance,money,coin]
    usage: /coins
  server:
    description: join server commands
    aliases: [server, serv]
    usage: /server